### ISSUE TITLE
MemoryError in sif_embedding.py

### ISSUE THREAD

**Issue by silvioOlivastri** [PrincetonML/SIF#13]
Hi,

I downloaded and unzipped `glove.840B.300d.zip` file and than I run `python sif_embedding.py`.
After 30 minutes I receive this error:

```
Traceback (most recent call last):
  File "sif_embedding.py", line 15, in <module>
    (words, We) = data_io.getWordmap(wordfile)
  File "../src/data_io.py", line 22, in getWordmap
    return (words, np.array(We))
MemoryError
```

Have you ever seen this error?

Nb: I drop the process after Termial shows this error because the process goes in deadlock/loop (I'm sure it doesn't go forward).

**Comment by silvioOlivastri** [comment]
I resolve this issues!
I can change the function `data_io.getWordmap(..)`:
```
def getWordmap(textfile):
    words={}
    We = []
    with open(textfile,'r') as f:
        n = 0
        for line in f:
            i = line.split()
            j = 1
            v = []
            while j < len(i):
                v.append(float(i[j]))
                j += 1
            words[i[0]]=n
            We.append(v)
            n+=1
    return (words, np.array(We))
```
