### ISSUE TITLE
Mention proper version of dependency in requirements.text file

### ISSUE THREAD

**Issue by mayankg53** [PrincetonML/SIF#17]
Hi,
Can you please mention the versions also in the dependencies because sometimes there is a conflict of methods in different versions and I face the same in theano. It will be really helpful.

Secondly, it will be good if you also mention the minimum memory requirements for the GPU also to run the basic demo script.

**Comment by tuzhucheng** [comment]
Yes I am also getting error seemingly due to version issue.

```
sentiment
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    import lasagne
  File "/u3/z3tu/anaconda3/envs/sif/lib/python2.7/site-packages/lasagne/__init__.py", line 19, in <module>
    from . import layers
  File "/u3/z3tu/anaconda3/envs/sif/lib/python2.7/site-packages/lasagne/layers/__init__.py", line 7, in <module>
    from .pool import *
  File "/u3/z3tu/anaconda3/envs/sif/lib/python2.7/site-packages/lasagne/layers/pool.py", line 6, in <module>
    from theano.tensor.signal import downsample
ImportError: cannot import name downsample
```

**Comment by kmario23** [comment]
Hello guys,
   I created a conda env with the following packages and then the code runs without any issues.

```
# packages in environment at /home/kmario23/anaconda3/envs/sif:
certifi                   2016.2.28                py27_0  
lasagne                   0.1                      py27_0  
libgfortran               3.0.0                         1  
mkl                       11.3.3                        0  
numpy                     1.10.4                   py27_2  
openssl                   1.0.2l                        0  
pip                       9.0.1                    py27_1  
python                    2.7.13                        0  
readline                  6.2                           2  
scikit-learn              0.17.1              np110py27_2  
scipy                     0.17.1              np110py27_1  
setuptools                36.4.0                   py27_1  
sqlite                    3.13.0                        0  
theano                    0.7.0               np110py27_0  
tk                        8.5.18                        0  
wheel                     0.29.0                   py27_0  
zlib                      1.2.11                        0  

```
